version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - booksystem-api
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    volumes:
      - "pg-vol:/var/lib/postgres"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - booksystem-api
    healthcheck:
      test: [ "CMD", "pgadmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  booksystem-api:
    driver: bridge
volumes:
  pg-vol:
